"""Per-rep commission statement generation.

Generates one statement file PER payee, per period. Each file contains ONLY
that payee's data — no other payee's id, name, or amounts may appear.

Formats: xlsx, html (branded, print-ready), pdf (optional fpdf2 extra).

Look & branding are controlled by a `StatementTheme` (company name, logo, accent
colour, currency symbol, contact line, section toggles, white-label switch). An
admin can keep a `theme.yaml` and pass it on the command line; defaults reproduce
the plain built-in style.
"""

from __future__ import annotations

import html
import re
from collections.abc import Callable
from dataclasses import dataclass
from datetime import date
from decimal import Decimal
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from icm_engine.rounding import RoundingMode, round_money

_DEFAULT_ROUNDING = RoundingMode.HALF_UP

_MONTHS = (
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December",
)


class StatementTheme(BaseModel):
    """Branding/look for rep statements. Every field has a safe default, so an
    empty theme renders the plain built-in style. Load from YAML with
    `load_statement_theme`, or pass `icm statements --theme theme.yaml`."""

    company_name: str = ""                       # shown in the header; blank = none
    logo_url: str = ""                           # header logo (URL, relative path, or data URI)
    accent_color: str = "#1d4ed8"                # themes the top rule, total, and attainment bar
    currency_symbol: str = "$"                   # amount prefix (e.g. "£", "€")
    title: str = "Commission statement"          # the document label
    earned_label: str = "Total commission"       # caption above the headline figure
    contact_line: str = "Questions? Contact your manager."
    footer_note: str = ""                        # optional extra footer line
    show_attainment: bool = True
    show_line_explanations: bool = True          # the plain-English "why you earned this" under each deal
    show_powered_by: bool = True                 # "Generated by OpenIncent" — turn off to white-label

    @property
    def safe_accent(self) -> str:
        """Accent colour, validated to a CSS hex; falls back to the default."""
        c = (self.accent_color or "").strip()
        if re.fullmatch(r"#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6}", c):
            return c
        return "#1d4ed8"


def load_statement_theme(path: str | Path) -> StatementTheme:
    """Load a StatementTheme from a YAML file (admin-editable branding)."""
    import yaml

    data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path}: theme file must be a mapping of fields to values")
    return StatementTheme.model_validate(data)


@dataclass
class StatementFile:
    payee_id: str
    period: str | None
    path: Path
    fmt: str  # "xlsx" | "html" | "pdf"


# ------------------------------------------------------------------
# Public API
# ------------------------------------------------------------------


def generate_statements(
    commissions: list[Any],
    payees: list[Any],
    *,
    out_dir: Path,
    period: str | None = None,
    formats: tuple[str, ...] = ("xlsx",),
    generated_on: date | None = None,
    emit_zero: bool = False,
    attainment: list[Any] | None = None,
    plan_name: str = "",
    rounding_mode: RoundingMode = _DEFAULT_ROUNDING,
    rounding_places: int = 2,
    rates: dict[str, Decimal] | None = None,
    reporting_currency: str = "",
    source_currency: str = "",
    theme: StatementTheme | None = None,
) -> list[StatementFile]:
    """Generate per-payee commission statements.

    Args:
        commissions: Commission objects with payee_id, period, transaction_id,
                     origin_period, rule_id, base_amount, rate, commission_amount,
                     notes.
        payees: Payee objects with id, name.
        out_dir: Output directory.
        period: If set, filter to this period only.
        formats: Which formats to generate ("xlsx", "html", "pdf").
        generated_on: Injectable date for deterministic output.
        emit_zero: If True, emit zero statements for payees with no lines.
        attainment: AttainmentSummary objects for attainment display.
        plan_name: Plan name for the statement header.
        theme: Branding/look. Defaults to the plain built-in style.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    theme = theme or StatementTheme()

    # Build payee lookup
    payee_map: dict[str, Any] = {}
    for p in payees:
        pid = getattr(p, "id", None)
        if pid is None and hasattr(p, "get"):
            pid = p.get("id", "")
        payee_map[pid or ""] = p

    # Group commissions by payee_id
    by_payee: dict[str, list[Any]] = {}
    for c in commissions:
        pid = _get_attr(c, "payee_id")
        c_period = _get_attr(c, "period")
        if period and c_period != period:
            continue
        by_payee.setdefault(pid, []).append(c)

    # Get all payee ids to process
    all_pids = set(by_payee.keys())
    if emit_zero:
        all_pids.update(payee_map.keys())

    files: list[StatementFile] = []
    period_label = period or "all"

    # A single display formatter: convert (if a reporting currency is set)
    # then round to the configured mode/places. Passed into every writer so
    # statements honour the plan's rounding policy and reconcile line-to-total.
    _rm = rounding_mode
    _places = rounding_places
    _rates = dict(rates or {})
    _rc = (reporting_currency or "").strip().upper()
    _sc = (source_currency or "").strip().upper()

    def _round_disp(amount: Decimal) -> Decimal:
        from icm_engine.currency import convert as _convert
        amt = amount
        if _rc and _sc and _sc != _rc:
            try:
                amt = _convert(amount, _sc, _rc, _rates, rounding=_rm)
            except KeyError:
                pass  # fall through — display in original currency
        return round_money(amt, _rm, _places)

    def _fmt(amount: Decimal) -> str:
        return str(_round_disp(amount))

    for pid in sorted(all_pids):
        lines = by_payee.get(pid, [])
        if not lines and not emit_zero:
            continue

        p = payee_map.get(pid)
        pname = _get(p, "name", pid) if p else pid
        # Total = sum of the per-line DISPLAY amounts, so the statement
        # reconciles to the penny against its own line items.
        total = sum(
            (_round_disp(Decimal(_get_attr(c, "commission_amount", "0")))
            for c in lines),
            Decimal("0")
        )
        total_str = str(total)

        # Find attainment for this payee
        payee_attainment: Any = None
        if attainment:
            for a in attainment:
                if _get_attr(a, "payee_id") == pid:
                    payee_attainment = a
                    break

        for fmt in formats:
            if fmt == "xlsx":
                path = _write_xlsx(pid, pname, period_label, lines, total_str, out_dir,
                                   _d=_fmt, plan_name=plan_name, attainment=payee_attainment,
                                   theme=theme)
            elif fmt == "html":
                path = _write_html(pid, pname, period_label, lines, total_str, generated_on, out_dir,
                                   _d=_fmt, plan_name=plan_name, attainment=payee_attainment,
                                   theme=theme)
            elif fmt == "pdf":
                path = _write_pdf(pid, pname, period_label, lines, total_str, generated_on, out_dir,
                                  _d=_fmt, plan_name=plan_name, attainment=payee_attainment,
                                  theme=theme)
            else:
                raise ValueError(f"Unknown format: {fmt}")
            files.append(StatementFile(payee_id=pid, period=period, path=path, fmt=fmt))

    return files


def _period_label(period: str) -> str:
    """'2026-01' -> 'January 2026'; 'all' -> 'All periods'; else unchanged."""
    if period == "all":
        return "All periods"
    m = re.fullmatch(r"(\d{4})-(\d{2})", period)
    if m:
        yr, mo = int(m.group(1)), int(m.group(2))
        if 1 <= mo <= 12:
            return f"{_MONTHS[mo - 1]} {yr}"
    return period


# ------------------------------------------------------------------
# Adjustment detection
# ------------------------------------------------------------------


def _adj_label(c: Any, pid: str) -> str:
    """Return an adjustment label if this line is an adjustment/cap/draw/manual."""
    rule_id = _get(c, "rule_id", "")
    notes = _get(c, "notes", "")
    origin = _get(c, "origin_period", "")
    c_period = _get(c, "period", "")
    amount = _get_dec(c, "commission_amount")

    # Explicit rule IDs take priority
    if rule_id == "manual_adjustment":
        return "Manual Adj"
    if rule_id in ("payout_cap", "cap_adjustment"):
        return "Cap"
    if rule_id == "draw":
        if amount < 0:
            return "Draw Recovery"
        return "Draw Top-up"

    # Heuristics from notes/content
    if amount < 0:
        return "Clawback"
    if "true_up" in notes.lower() or (origin and origin != c_period):
        return f"True-up from {origin}" if origin else "True-up"
    return ""


# ------------------------------------------------------------------
# XLSX
# ------------------------------------------------------------------


def _write_xlsx(
    pid: str, pname: str, period: str,
    lines: list[Any], total_str: str, out_dir: Path,
    *, _d: Callable[[Decimal], str], plan_name: str = "", attainment: Any = None,
    theme: StatementTheme,
) -> Path:
    from icm_engine.excel import write_xlsx

    sym = theme.currency_symbol

    # Header info rows
    info_rows: list[dict[str, str]] = []
    if theme.company_name:
        info_rows.append({"Field": "Company", "Value": theme.company_name})
    info_rows.append({"Field": "Plan", "Value": plan_name or "-"})
    info_rows.append({"Field": "Payee", "Value": f"{pname} ({pid})"})
    info_rows.append({"Field": "Period", "Value": period})
    if attainment is not None:
        booked = _d(_get_dec(attainment, "bookings"))
        quota = _d(_get_dec(attainment, "quota"))
        pct_val = _get_attainment_pct(attainment)
        if pct_val is not None:
            pct_str = f"{pct_val * 100:.1f}%"
        else:
            pct_str = "N/A"
        info_rows.append({"Field": "Attainment", "Value": f"{sym}{booked} / {sym}{quota} ({pct_str})"})

    # Line items
    data_rows: list[dict[str, str]] = []
    for c in lines:
        adj = _adj_label(c, pid)
        row = {
            "transaction_id": _get(c, "transaction_id"),
            "deal_id": _get(c, "deal_id", ""),
            "product": _get(c, "product", ""),
            "rule_id": _get(c, "rule_id"),
            "base_amount": _d(_get_dec(c, "base_amount")),
            "rate": str(_get_dec(c, "rate")),
            "commission": _d(_get_dec(c, "commission_amount")),
            "adjustment": adj,
            "notes": _get(c, "notes", ""),
        }
        data_rows.append(row)

    # Total row
    data_rows.append({
        "transaction_id": "TOTAL",
        "deal_id": "",
        "product": "",
        "rule_id": "",
        "base_amount": "",
        "rate": "",
        "commission": total_str,
        "adjustment": "",
        "notes": "",
    })

    path = out_dir / f"statement_{pid}_{period}.xlsx"
    write_xlsx(path, {"Info": info_rows, "Statement": data_rows})
    return path


# ------------------------------------------------------------------
# HTML (branded, print-ready)
# ------------------------------------------------------------------

_STMT_CSS = """
*{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;
  color:var(--ink);margin:0;background:#f4f5f7;line-height:1.55;-webkit-font-smoothing:antialiased}
.sheet{max-width:720px;margin:28px auto;background:#fff;border:1px solid var(--line);border-radius:16px;
  overflow:hidden;box-shadow:0 1px 3px rgba(15,23,42,.06)}
.top{display:flex;align-items:center;justify-content:space-between;gap:16px;
  border-top:5px solid var(--accent);padding:22px 32px 18px}
.brand{display:flex;align-items:center;gap:12px;font-weight:800;font-size:18px;letter-spacing:-.01em;color:var(--ink)}
.brand img{height:32px;width:auto;display:block}
.doctype{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:.1em;color:var(--accent)}
.body{padding:6px 32px 0}
.who{margin:16px 0 2px;font-size:26px;font-weight:800;letter-spacing:-.02em}
.sub{color:var(--ink2);font-size:14px;margin:0 0 20px}
.hero{background:var(--soft);border:1px solid var(--line);border-radius:14px;padding:20px 24px;
  display:flex;align-items:flex-end;justify-content:space-between;gap:16px;flex-wrap:wrap}
.hero .lbl{font-size:13px;color:var(--ink2);font-weight:600}
.hero .amt{font-size:38px;font-weight:800;letter-spacing:-.02em;color:var(--accent);line-height:1.04;margin-top:3px}
.hero .who-id{font-size:12.5px;color:var(--ink2);text-align:right}
.att{margin:24px 0 2px}
.att .row{display:flex;justify-content:space-between;font-size:13px;color:var(--ink2);margin-bottom:7px}
.att .row b{color:var(--ink);font-weight:700}
.att .bar{height:10px;background:var(--line);border-radius:999px;overflow:hidden}
.att .fill{height:100%;background:var(--accent);border-radius:999px}
h2.sec{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink2);
  margin:30px 0 4px;font-weight:700}
.line{border-bottom:1px solid var(--line);padding:13px 0}
.line:last-child{border-bottom:0}
.line-h{display:flex;justify-content:space-between;align-items:baseline;gap:12px}
.line-deal{font-weight:650;font-size:15px}
.line-deal .prod{color:var(--ink2);font-weight:400}
.line-amt{font-weight:700;font-size:15px;font-variant-numeric:tabular-nums;white-space:nowrap}
.line-amt.neg{color:#b91c1c}
.line-note{color:var(--ink2);font-size:12.5px;margin-top:3px}
.badge{display:inline-block;background:#fff3cd;color:#856404;font-size:11px;font-weight:700;
  padding:1px 8px;border-radius:999px;margin-left:2px;vertical-align:1px}
.tot{display:flex;justify-content:space-between;align-items:baseline;border-top:2px solid var(--ink);
  margin-top:2px;padding:15px 0 4px;font-size:17px;font-weight:800}
.tot .amt{color:var(--accent)}
.foot{margin-top:30px;padding:18px 32px 26px;border-top:1px solid var(--line);color:var(--ink2);font-size:12.5px}
.foot p{margin:0 0 4px}
.foot .pb{margin-top:8px;font-size:11.5px;color:#9aa1ad}
@media print{
  body{background:#fff}
  .sheet{border:0;box-shadow:none;margin:0;max-width:none}
  .hero,.line{break-inside:avoid}
}
"""


def _write_html(
    pid: str, pname: str, period: str,
    lines: list[Any], total_str: str, generated_on: date | None, out_dir: Path,
    *, _d: Callable[[Decimal], str], plan_name: str = "", attainment: Any = None,
    theme: StatementTheme,
) -> Path:
    esc = html.escape
    sym = theme.currency_symbol
    accent = theme.safe_accent

    def money(v: str) -> str:
        return f"{sym}{v}"

    # --- header brand ---
    brand_bits = ""
    if theme.logo_url:
        brand_bits += f'<img src="{esc(theme.logo_url)}" alt="">'
    brand_bits += esc(theme.company_name) if theme.company_name else "Commission statement"

    # --- sub line ---
    sub = esc(_period_label(period))
    if plan_name:
        sub += f" &middot; {esc(plan_name)}"
    if generated_on:
        sub += f" &middot; generated {esc(str(generated_on))}"

    # --- attainment ---
    att_html = ""
    if theme.show_attainment and attainment is not None:
        booked = _d(_get_dec(attainment, "bookings"))
        quota = _d(_get_dec(attainment, "quota"))
        pct_val = _get_attainment_pct(attainment)
        pct = f"{pct_val * 100:.1f}%" if pct_val is not None else "N/A"
        width = "0"
        if pct_val is not None:
            width = f"{max(0.0, min(pct_val * 100, 100.0)):.1f}"
        att_html = (
            f'<div class="att"><div class="row">'
            f'<span>Quota attainment</span>'
            f'<span><b>{esc(pct)}</b> &middot; {money(esc(booked))} of {money(esc(quota))}</span>'
            f'</div><div class="bar"><div class="fill" style="width:{width}%"></div></div></div>'
        )

    # --- line items ---
    line_parts: list[str] = []
    for c in lines:
        adj = _adj_label(c, pid)
        base = _d(_get_dec(c, "base_amount"))
        rate = str(_get_dec(c, "rate"))
        comm_dec = _get_dec(c, "commission_amount")
        comm = _d(comm_dec)
        notes = str(_get(c, "notes", ""))
        tid = esc(str(_get(c, "transaction_id")))
        deal = esc(str(_get(c, "deal_id", "")))
        product = esc(str(_get(c, "product", "")))
        origin = esc(str(_get(c, "origin_period", "")))

        label = deal or tid
        prod_bit = f' <span class="prod">&middot; {product}</span>' if product else ""
        neg = " neg" if comm_dec < 0 else ""
        badge = f'<span class="badge">{esc(adj)}</span>' if adj else ""

        note_html = ""
        if theme.show_line_explanations:
            if notes:
                explanation = esc(notes)
            else:
                explanation = f"{money(esc(base))} &times; {esc(rate)}"
            if origin:
                explanation += f" &middot; from {origin}"
            note_html = f'<div class="line-note">{explanation} {badge}</div>'
        elif badge:
            note_html = f'<div class="line-note">{badge}</div>'

        line_parts.append(
            f'<div class="line"><div class="line-h">'
            f'<span class="line-deal">{label}{prod_bit}</span>'
            f'<span class="line-amt{neg}">{money(esc(comm))}</span>'
            f'</div>{note_html}</div>'
        )

    # --- footer ---
    foot_parts = [f"<p>This statement is confidential and intended only for {esc(pname)}.</p>"]
    contact = esc(theme.contact_line) if theme.contact_line else ""
    if theme.footer_note:
        contact = (contact + " &middot; " if contact else "") + esc(theme.footer_note)
    if contact:
        foot_parts.append(f"<p>{contact}</p>")
    if theme.show_powered_by:
        foot_parts.append('<p class="pb">Generated by OpenIncent</p>')

    root = (
        f"<style>:root{{--accent:{accent};--ink:#0f172a;--ink2:#5b6472;"
        f"--line:#e6e8ee;--soft:#f7f8fa}}\n{_STMT_CSS}</style>"
    )

    html_doc = (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f"<title>Commission statement — {esc(pname)}</title>\n{root}\n</head>\n<body>\n"
        '<div class="sheet">\n'
        f'  <div class="top"><div class="brand">{brand_bits}</div>'
        f'<div class="doctype">{esc(theme.title)}</div></div>\n'
        '  <div class="body">\n'
        f'    <div class="who">{esc(pname)}</div>\n'
        f'    <div class="sub">{sub}</div>\n'
        '    <div class="hero">\n'
        f'      <div><div class="lbl">{esc(theme.earned_label)}</div>'
        f'<div class="amt">{money(esc(total_str))}</div></div>\n'
        f'      <div class="who-id">{esc(pid)}</div>\n'
        '    </div>\n'
        f"    {att_html}\n"
        '    <h2 class="sec">Your deals</h2>\n'
        f'    {"".join(line_parts)}\n'
        f'    <div class="tot"><span>Total</span><span class="amt">{money(esc(total_str))}</span></div>\n'
        '  </div>\n'
        f'  <div class="foot">{"".join(foot_parts)}</div>\n'
        '</div>\n</body>\n</html>'
    )

    path = out_dir / f"statement_{pid}_{period}.html"
    path.write_text(html_doc, encoding="utf-8")
    return path


# ------------------------------------------------------------------
# PDF (optional fpdf2 extra)
# ------------------------------------------------------------------


def _hex_to_rgb(h: str) -> tuple[int, int, int]:
    h = h.lstrip("#")
    if len(h) == 3:
        h = "".join(ch * 2 for ch in h)
    if len(h) != 6:
        return (29, 78, 216)
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _write_pdf(
    pid: str, pname: str, period: str,
    lines: list[Any], total_str: str, generated_on: date | None, out_dir: Path,
    *, _d: Callable[[Decimal], str], plan_name: str = "", attainment: Any = None,
    theme: StatementTheme,
) -> Path:
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError(
            "PDF support requires fpdf2. Install with: pip install icm-engine[pdf] "
            "or: uv pip install fpdf2"
        ) from None

    sym = theme.currency_symbol
    ar, ag, ab = _hex_to_rgb(theme.safe_accent)
    col_w = {"txn": 34, "rule": 24, "base": 28, "rate": 16, "comm": 28, "adj": 28}

    pdf = FPDF()
    pdf.add_page()
    # Accent header band
    pdf.set_fill_color(ar, ag, ab)
    pdf.rect(0, 0, 210, 3, style="F")
    if theme.company_name:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(ar, ag, ab)
        pdf.cell(0, 9, theme.company_name, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(20, 20, 30)
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, theme.title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, f"{pname} ({pid})  -  Plan: {plan_name or '-'}  -  Period: {_period_label(period)}",
             new_x="LMARGIN", new_y="NEXT")
    if theme.show_attainment and attainment is not None:
        booked = _d(_get_dec(attainment, "bookings"))
        quota = _d(_get_dec(attainment, "quota"))
        pct_val = _get_attainment_pct(attainment)
        pct = f"{pct_val * 100:.1f}%" if pct_val is not None else "N/A"
        pdf.cell(0, 5, f"Attainment: {sym}{booked} / {sym}{quota} ({pct})",
                 new_x="LMARGIN", new_y="NEXT")
    if generated_on:
        pdf.cell(0, 5, f"Generated: {generated_on}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Table header
    pdf.set_font("Helvetica", "B", 8)
    headers = ("Txn", "Rule", "Base", "Rate", "Comm", "Adj")
    for h, w in zip(headers, col_w.values(), strict=True):
        pdf.cell(w, 6, h, border=1)
    pdf.ln()

    # Rows
    pdf.set_font("Helvetica", "", 8)
    for c in lines:
        adj = _adj_label(c, pid)
        row = (
            str(_get(c, "transaction_id"))[:20],
            str(_get(c, "rule_id"))[:12],
            f"{sym}{_d(_get_dec(c, 'base_amount'))}",
            str(_get_dec(c, "rate")),
            f"{sym}{_d(_get_dec(c, 'commission_amount'))}",
            adj[:18] if adj else "",
        )
        for val, w in zip(row, col_w.values(), strict=True):
            pdf.cell(w, 5, val, border=1)
        pdf.ln()

    # Total
    pdf.set_font("Helvetica", "B", 8)
    label_w = sum(list(col_w.values())[:4])
    pdf.cell(label_w, 6, "Total", border=1)
    pdf.cell(col_w["comm"], 6, f"{sym}{total_str}", border=1, align="R")
    pdf.cell(col_w["adj"], 6, "", border=1)
    pdf.ln(6)

    # Confidentiality footer
    pdf.set_font("Helvetica", "I", 7)
    pdf.cell(0, 4, f"This statement is confidential and intended only for {pname}.",
             new_x="LMARGIN", new_y="NEXT")
    foot = theme.contact_line or ""
    if theme.footer_note:
        foot = (foot + "  |  " if foot else "") + theme.footer_note
    if theme.show_powered_by:
        foot = (foot + "  |  " if foot else "") + "Generated by OpenIncent"
    if foot:
        pdf.cell(0, 4, foot, new_x="LMARGIN", new_y="NEXT")

    path = out_dir / f"statement_{pid}_{period}.pdf"
    pdf.output(str(path))
    return path


# ------------------------------------------------------------------
# Helpers for attribute/dict access
# ------------------------------------------------------------------


def _get_attr(obj: Any, attr: str, default: str = "") -> str:
    """Safely get a string attribute from an object or dict."""
    if hasattr(obj, attr):
        return str(getattr(obj, attr))
    if isinstance(obj, dict):
        return str(obj.get(attr, default))
    return default


def _get(obj: Any, attr: str, default: str = "") -> str:
    return _get_attr(obj, attr, default)


def _get_dec(obj: Any, attr: str) -> Decimal:
    val = _get(obj, attr, "0")
    return Decimal(val)


def _get_attainment_pct(attainment: Any) -> float | None:
    """Safely extract attainment_pct as a float, or None."""
    raw = getattr(attainment, "attainment_pct", None)
    if raw is None:
        return None
    return float(str(raw))
