"""StatementTheme: model defaults, YAML loading, and themed rendering."""

from datetime import date
from decimal import Decimal
from pathlib import Path

import pytest

from icm_engine.engine import CommissionEngine
from icm_engine.models import (
    FlatRateRule,
    Payee,
    Plan,
    Transaction,
)
from icm_engine.statements import (
    StatementTheme,
    generate_statements,
    load_statement_theme,
)


def _payee(**overrides):
    defaults = dict(
        id="P001", name="Alice", quota=Decimal("0"), plan_id="p",
        effective_from=date(2026, 1, 1),
    )
    return Payee(**(defaults | overrides))


def _run(quota: str = "0"):
    plan = Plan(plan_id="p", name="P", period_type="monthly", currency="USD",
                rules=[FlatRateRule(type="flat_rate", id="R1", rate=Decimal("0.05"))])
    payees = [_payee(id="P1", name="Alice", quota=Decimal(quota))]
    txns = [
        Transaction(id="T1", payee_id="P1", period="2026-01", amount=Decimal("10000"),
                    close_date=date(2026, 1, 10)),
    ]
    return CommissionEngine().calculate(plan, txns, payees), payees


class TestThemeModel:
    def test_defaults_reproduce_plain_style(self) -> None:
        t = StatementTheme()
        assert t.company_name == ""
        assert t.currency_symbol == "$"
        assert t.title == "Commission statement"
        assert t.show_attainment and t.show_line_explanations and t.show_powered_by
        assert t.safe_accent == "#1d4ed8"

    def test_safe_accent_accepts_valid_hex(self) -> None:
        assert StatementTheme(accent_color="#0a0").safe_accent == "#0a0"
        assert StatementTheme(accent_color="#00AA22").safe_accent == "#00AA22"

    @pytest.mark.parametrize("bad", ["red", "#12345g", "#12345", "url(x)", "", "  "])
    def test_safe_accent_falls_back_on_garbage(self, bad: str) -> None:
        assert StatementTheme(accent_color=bad).safe_accent == "#1d4ed8"


class TestLoadTheme:
    def test_yaml_round_trip(self, tmp_path: Path) -> None:
        f = tmp_path / "theme.yaml"
        f.write_text(
            "company_name: Acme Staffing\n"
            "accent_color: '#0a0'\n"
            "currency_symbol: £\n"
            "show_powered_by: false\n",
            encoding="utf-8",
        )
        t = load_statement_theme(f)
        assert t.company_name == "Acme Staffing"
        assert t.safe_accent == "#0a0"
        assert t.currency_symbol == "£"
        assert t.show_powered_by is False
        # untouched fields keep their defaults
        assert t.contact_line == "Questions? Contact your manager."

    def test_empty_file_is_all_defaults(self, tmp_path: Path) -> None:
        f = tmp_path / "theme.yaml"
        f.write_text("", encoding="utf-8")
        assert load_statement_theme(f) == StatementTheme()

    def test_non_mapping_raises(self, tmp_path: Path) -> None:
        f = tmp_path / "theme.yaml"
        f.write_text("- just\n- a\n- list\n", encoding="utf-8")
        with pytest.raises(ValueError, match="mapping"):
            load_statement_theme(f)


class TestThemedHtml:
    def test_branding_flows_into_html(self) -> None:
        result, payees = _run(quota="20000")
        out = Path("tests/fixtures/_stmt_theme")
        out.mkdir(parents=True, exist_ok=True)

        theme = StatementTheme(
            company_name="Acme Staffing",
            logo_url="logo.png",
            accent_color="#0a0",
            currency_symbol="£",
            footer_note="Payroll ref 42",
            show_powered_by=False,
        )
        files = generate_statements(
            result.commissions, payees, out_dir=out, formats=("html",),
            attainment=result.attainment, theme=theme,
        )
        html = files[0].path.read_text(encoding="utf-8")

        assert "Acme Staffing" in html
        assert 'src="logo.png"' in html
        assert "--accent:#0a0" in html
        assert "£500.00" in html  # 10000 × 0.05, themed symbol
        assert "Payroll ref 42" in html
        assert "Quota attainment" in html  # attainment block on by default
        assert "Generated by OpenIncent" not in html  # white-label switch

    def test_default_theme_keeps_plain_style(self) -> None:
        result, payees = _run()
        out = Path("tests/fixtures/_stmt_theme2")
        out.mkdir(parents=True, exist_ok=True)

        files = generate_statements(
            result.commissions, payees, out_dir=out, formats=("html",),
        )
        html = files[0].path.read_text(encoding="utf-8")

        assert "Commission statement" in html  # brand falls back to doc label
        assert "$500.00" in html
        assert "Generated by OpenIncent" in html

    def test_section_toggles_remove_content(self) -> None:
        result, payees = _run(quota="20000")
        out = Path("tests/fixtures/_stmt_theme3")
        out.mkdir(parents=True, exist_ok=True)

        theme = StatementTheme(show_attainment=False, show_line_explanations=False)
        files = generate_statements(
            result.commissions, payees, out_dir=out, formats=("html",),
            attainment=result.attainment, theme=theme,
        )
        html = files[0].path.read_text(encoding="utf-8")

        assert "Quota attainment" not in html
        assert '<div class="line-note">' not in html

    def test_company_name_is_escaped(self) -> None:
        result, payees = _run()
        out = Path("tests/fixtures/_stmt_theme4")
        out.mkdir(parents=True, exist_ok=True)

        theme = StatementTheme(company_name="<script>alert(1)</script>")
        files = generate_statements(
            result.commissions, payees, out_dir=out, formats=("html",), theme=theme,
        )
        html = files[0].path.read_text(encoding="utf-8")

        assert "<script>alert(1)</script>" not in html
        assert "&lt;script&gt;" in html


class TestThemedXlsx:
    def test_company_row_present_when_set(self) -> None:
        from icm_engine.excel import read_xlsx_rows

        result, payees = _run()
        out = Path("tests/fixtures/_stmt_theme5")
        out.mkdir(parents=True, exist_ok=True)

        theme = StatementTheme(company_name="Acme Staffing")
        files = generate_statements(
            result.commissions, payees, out_dir=out, formats=("xlsx",), theme=theme,
        )
        _headers, rows = read_xlsx_rows(files[0].path)
        flat = [str(v) for row in rows for v in row.values()]
        assert "Acme Staffing" in flat
